#!/usr/bin/env python
# deploy-cleanup -- remove all but the latest four deployed versions
# from the file system

import os
import re
import shutil
import sys

PROJECT=sys.argv[1]
HOME=os.environ['HOME']

# Read recent history from deploy.log
log=open(os.path.join(HOME, 'deploy.log'), 'r')
assert log
entries = log.readlines()[-2:]
log.close()

# Just keep the dir names
entries = [e.split(' ')[0] for e in entries]

# Read the current link
current = os.path.basename(os.readlink(os.path.join(HOME, PROJECT)))

PATTERN=re.compile('^%s-[0-9A-Fa-f]+$' % PROJECT)

# Read the home dir
for d in os.listdir(HOME):
    f = os.path.join(HOME, d)
    if PATTERN.match(d) and os.path.isdir(f):
        if d == current:
            print "Keeping  " + f + " (current)"
        elif d in entries:
            print "Keeping  " + f + " (recent)"
        else:
            print "Removing " + f
            shutil.rmtree(f)
