#!/bin/bash
# git pre-receive hook to deploy to uwsgi "emperor" mode

# Path to compiled, setuid "vassalconf" program
SELF=`readlink -f $0`
DEPLOY=`dirname $SELF`/deploy-version

# Stop if any command produces non-zero return status
set -e

# Determine project name from bare repo directory basename
REPO=`pwd`
PROJECT=`basename "$REPO" .git`

# Determine commit from standard input
COMMIT=
while read LINE; do
    NEW=`echo $LINE|cut -f2 -d' '`
    REF=`echo $LINE|cut -f3 -d' '`
    if [[ "$REF" == "refs/heads/master" ]]; then
        COMMIT=`echo $NEW|cut -c1-6`
    fi
done

if [[ "$COMMIT" == "" ]]; then
    echo No update to master
    exit 0
fi

# Working dir is named after project and prefix of commit hash.
WORKDIR=$HOME/$PROJECT-$COMMIT
echo "Checking out $WORKDIR..."
mkdir -p $WORKDIR
git archive $COMMIT | tar -x -C $WORKDIR

# Do it!
$DEPLOY $WORKDIR
date +"$PROJECT-$COMMIT %F %T" >> $HOME/deploy.log
